CREATE TABLE shows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price_paise BIGINT NOT NULL CHECK (price_paise >= 0),
    per_user_limit INTEGER NOT NULL DEFAULT 4 CHECK (per_user_limit > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_shows_name_not_blank CHECK (char_length(trim(name)) > 0)
);

CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id BIGINT NOT NULL REFERENCES shows (id),
    user_id VARCHAR(255) NOT NULL,
    amount_paise BIGINT NOT NULL CHECK (amount_paise >= 0),
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_reservations_status CHECK (status IN ('CONFIRMED', 'CANCELLED')),
    CONSTRAINT chk_reservations_cancelled_at CHECK (
        (status = 'CONFIRMED' AND cancelled_at IS NULL)
        OR (status = 'CANCELLED' AND cancelled_at IS NOT NULL)
    )
);

CREATE TABLE seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id BIGINT NOT NULL REFERENCES shows (id),
    seat_number VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE',
    reservation_id BIGINT REFERENCES reservations (id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_seats_show_seat_number UNIQUE (show_id, seat_number),
    CONSTRAINT chk_seats_status CHECK (status IN ('AVAILABLE', 'HELD', 'CONFIRMED')),
    CONSTRAINT chk_seats_reservation_assignment CHECK (
        (status = 'AVAILABLE' AND reservation_id IS NULL)
        OR (status IN ('HELD', 'CONFIRMED') AND reservation_id IS NOT NULL)
    )
);

CREATE TABLE reservation_seats (
    reservation_id BIGINT NOT NULL REFERENCES reservations (id),
    seat_id BIGINT NOT NULL REFERENCES seats (id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (reservation_id, seat_id)
);

CREATE TABLE idempotency_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    show_id BIGINT NOT NULL REFERENCES shows (id),
    idempotency_key VARCHAR(255) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    reservation_id BIGINT REFERENCES reservations (id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_idempotency_keys_user_show_key UNIQUE (user_id, show_id, idempotency_key)
);

CREATE TABLE user_show_limits (
    show_id BIGINT NOT NULL REFERENCES shows (id),
    user_id VARCHAR(255) NOT NULL,
    reserved_count INTEGER NOT NULL DEFAULT 0 CHECK (reserved_count >= 0),
    reservation_limit INTEGER NOT NULL CHECK (reservation_limit > 0),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (show_id, user_id),
    CONSTRAINT chk_user_show_limits_count CHECK (reserved_count <= reservation_limit)
);

CREATE INDEX idx_seats_show_status_id ON seats (show_id, status, id);
CREATE INDEX idx_reservations_show_status ON reservations (show_id, status);
CREATE INDEX idx_reservations_user_show ON reservations (user_id, show_id);
CREATE INDEX idx_reservation_seats_seat_id ON reservation_seats (seat_id);
